### PR TITLE
Removing the use of TriggerEventMeta inside the sdk, deprecating it t…

### PR DESCRIPTION
**Pull request by stabby-r7**
…o old komand only

So, this is causing problems with triggers in ICON - they need a different meta struct.

The marshaling here is losing us data

In every place BUT triggers, it's all pass-through json.RawMessage

We serialized it in trigger data so it could match the TriggerEvent response object, which old komand used to get pre-marshalled in an easy struct. But that will have to change so only old komand does that, and ICON does it it's own way with it's own struct.

Plugins never care what is in meta - it's a boomerang. goes in, comes back untouched.

This codifies that correctly and undoes my shortsightedness when ensuring the go sdk worked with ICON

### CODE REVIEW

**Comment by stabby-r7** [comment]
This has not yet been tested, i'm regenerating a plugin with it now

**Comment by stabby-r7** [comment]
Regen works but since the code isn't released, vendor gets the old copy which doesn't compile, but editting vendor by hand to fix the one typedef fixes the build, so this is just an order of ops problem that is solved by the natural flow of time.

Moving into testing the trigger in old k

**Comment by stabby-r7** [comment]
The regenerated timer trigger still works in old K but that is only half the story. old k is using a vendored SDK, but the changes w/r/t the updated SDK are limited to one place where we need to do an extra marshal step, so once we release the sdk2 update, i can vendor it and test again.

But i have 3 timers running over 2 workflows - and they all appear to coming in and attributing correctly, meaning this change inside the plugin itself was done correctly.

**Comment by stabby-r7** [comment]
Alright so - I'm confident these changes are correct at this point, but we need to release them so we can finish off the rest of the work

**Comment by mikeatlas-r7** [comment]
Nice change 👍

**Pull request merged**
