### PR TITLE
Adding explicit ordering to username/pass and domain/token so they pr…

### PR DESCRIPTION
**Pull request by stabby-r7**
…esent in the ui in a sensible way to users

JIRA incoming

This was tested in our staging env

### CODE REVIEW

**Comment by mrinehart-r7** [comment]
Looks harmless to me

**Comment by stabby-r7** [comment]
lol does this still use travis

**Comment by mrinehart-r7** [comment]
> lol does this still use travis

Yes. We've left the Go SDK alone for the most part :P I doubt the Travis stuff even still works tbh.

**Comment by stabby-r7** [comment]
it does not seem to

**Comment by stabby-r7** [comment]
May need to remove the checks from travis.

Also, the r7/komand repo still depends on this but i almost feel like that dependency needs to move to icon-plugin now...

**Pull request closed without merging**
