### PR TITLE
DF-1604: Remove make deps from Dockerfile

### PR DESCRIPTION
**Pull request by mrinehart-r7**

### CODE REVIEW

**Comment by stabby-r7** [comment]
```
deps:
    go build -o $(GOPATH)/bin/go-bindata ./vendor/github.com/rapid7/go-bindata/go-bindata
    go get golang.org/x/tools/cmd/goimports
    go get -u honnef.co/go/tools/cmd/gosimple
    go get -u honnef.co/go/tools/cmd/staticcheck
    go get -u honnef.co/go/tools/cmd/unused
    go get -u github.com/golang/dep/cmd/dep
```

@jandre-r7 @jschipp-r7 @rnanopoulos-r7 

Can you think of any reason we need these run inside the docker ctr build process? Currently goimports is failing to build but i don't think we actually need it in the built ctr?

**Comment by jschipp-r7** [comment]
@stabby-r7 I'm unsure. Anyone else know? @rnanopoulos-r7 @jandre-r7

**Comment by stabby-r7** [comment]
I think it's fine - i really don't think anything in deps is used inside the container?

Looking at the Dockerfile, it runs `make plugin` which ultimately ferries to `make build` which does:

```
	@echo "Using repo $(REPO)"
	test -d $(GOPATH)/src/$(REPO) || ln -s $(PWD) $(GOPATH)/src/$(REPO) 
	mkdir -p bin
	go build -o bin/$(NAME) $(GOPATH)/src/$(REPO)/cmd/main.go
```
I think we're good to remove that make deps thing unless i'm super missing a thing..

**Comment by jschipp-r7** [comment]
Let's merge it and we can find out :)

**Pull request closed without merging**
